// ─── Machias Bay Region — Town Community Profiles ────────────────────────────
// Source: 2020 US Census, ACS 5-Year Estimates, Sunrise County Economic Council,
//         Maine DACF, and local municipal records.

export const TOWN_PROFILES = {
  Machias: {
    town_name: 'Machias',
    county: 'Washington County',
    population: 2371,
    median_age: 44.2,
    households: 1082,
    median_household_income: 41250,
    labor_force: 1150,
    employment: 1040,
    major_employers: [
      'Down East Community Hospital',
      'University of Maine at Machias',
      'Washington County Community College',
      'Town of Machias',
      'Washington County government',
      'Hannaford Supermarket',
    ],
    industry_sectors: ['Healthcare', 'Education', 'Government', 'Retail', 'Professional Services'],
    education_levels: {
      high_school_or_higher: '91%',
      bachelors_or_higher: '29%',
    },
    housing_units: 1196,
    housing_occupancy: '90.5%',
    median_home_value: 148200,
    transportation_access: 'US Route 1 corridor; no rail; regional air via Bangor (110 mi). Washington County Community Transportation.',
    broadband_availability: 'Partial — fiber available in downtown core; rural gaps persist.',
    water_access: 'Public water system; Machias River frontage',
    working_waterfront: false,
    commercial_fishing_presence: false,
    aquaculture_presence: false,
    tourism_assets: [
      'Burnham Tavern (1770, oldest building in Maine east of Kennebec)',
      'Bad Little Falls Park',
      'Machias River corridor',
      'O\'Brien Cemetery',
      'Centre Street Congregational Church',
    ],
    natural_resources: ['Machias River', 'Bold Coast proximity', 'Spruce/fir forest'],
    parks_and_recreation: ['Bad Little Falls Park', 'Machias River Trail', 'Helen\'s Restaurant heritage site'],
    local_institutions: [
      'University of Maine at Machias',
      'Washington County Community College',
      'Down East Community Hospital',
      'Washington County Court House',
      'Machias Savings Bank',
    ],
    school_system: 'SAD 37 — Machias Memorial High School, Rose M. Gaffney Elementary',
    healthcare_access: 'Down East Community Hospital (critical access); primary care, emergency dept.',
    municipal_services: 'Full municipal services — police, fire, EMS, public works, wastewater',
    economic_development_opportunities: [
      'Regional service hub for Washington County',
      'UMM / WCCC student population and workforce pipeline',
      'Downtown revitalization along Main Street',
      'Tourism gateway to Bold Coast',
      'Broadband expansion',
    ],
    community_assets: [
      'County seat — administrative center',
      'Higher education anchor institutions',
      'Hospital anchor',
      'River and natural landscape',
      'Historic downtown',
    ],
    community_challenges: [
      'Population decline and aging demographics',
      'Limited broadband in outlying areas',
      'Workforce housing shortage',
      'State poverty rate above state median',
      'Distance from major markets',
    ],
    planning_priorities: [
      'Downtown revitalization',
      'Affordable workforce housing',
      'Broadband infrastructure',
      'Economic diversification',
      'Regional service consolidation',
    ],
    regional_connections: ['East Machias', 'Whitneyville', 'Marshfield', 'Wesley', 'Northfield'],
    profile_url: 'https://sunrisecounty.org/communities/machias/',
    planning_map_url: 'https://scec.maps.arcgis.com/apps/mapviewer/index.html?webmap=dbd95bc183e94c1181a7d0fb3e8c5010',
  },

  'East Machias': {
    town_name: 'East Machias',
    county: 'Washington County',
    population: 1317,
    median_age: 47.1,
    households: 603,
    median_household_income: 38750,
    labor_force: 590,
    employment: 540,
    major_employers: [
      'East Machias school system',
      'Local agriculture and forestry operations',
      'Small retail and service businesses',
    ],
    industry_sectors: ['Agriculture', 'Forestry', 'Construction', 'Government', 'Retail'],
    education_levels: {
      high_school_or_higher: '87%',
      bachelors_or_higher: '18%',
    },
    housing_units: 712,
    housing_occupancy: '84.7%',
    median_home_value: 118500,
    transportation_access: 'US Route 1; rural road network. Relies on Machias for services.',
    broadband_availability: 'Limited — primarily DSL; significant rural gaps.',
    water_access: 'Private wells; East Machias River frontage',
    working_waterfront: false,
    commercial_fishing_presence: false,
    aquaculture_presence: false,
    tourism_assets: ['East Machias River fishing', 'Rural countryside'],
    natural_resources: ['East Machias River', 'Agricultural land', 'Forest land'],
    parks_and_recreation: ['East Machias River recreational fishing', 'Rural trails'],
    local_institutions: ['East Machias Town Office', 'Local churches'],
    school_system: 'AOS 96 — Grades K-8 locally; secondary in Machias',
    healthcare_access: 'Relies on Down East Community Hospital in Machias',
    municipal_services: 'Basic municipal — fire, road maintenance; contracts some services with Machias',
    economic_development_opportunities: [
      'Forest products and value-added wood manufacturing',
      'Agricultural expansion',
      'Rural broadband',
      'Proximity to Machias employment center',
    ],
    community_assets: ['River access', 'Rural character', 'Agricultural land base', 'Low cost of living'],
    community_challenges: [
      'Population decline',
      'Limited employment base',
      'Aging infrastructure',
      'Broadband gaps',
      'Limited municipal revenue',
    ],
    planning_priorities: [
      'Infrastructure maintenance',
      'Broadband access',
      'Housing condition improvement',
      'Economic base diversification',
    ],
    regional_connections: ['Machias', 'Whitneyville', 'Marshfield'],
    profile_url: 'https://sunrisecounty.org/communities/east-machias/',
    planning_map_url: null,
  },

  'Roque Bluffs': {
    town_name: 'Roque Bluffs',
    county: 'Washington County',
    population: 299,
    median_age: 53.8,
    households: 157,
    median_household_income: 47500,
    labor_force: 120,
    employment: 115,
    major_employers: ['State of Maine (Roque Bluffs State Park)', 'Remote/telecommute workers', 'Tourism seasonal'],
    industry_sectors: ['Tourism', 'Recreation', 'Government', 'Remote work'],
    education_levels: {
      high_school_or_higher: '92%',
      bachelors_or_higher: '32%',
    },
    housing_units: 246,
    housing_occupancy: '63.8%',
    median_home_value: 198000,
    transportation_access: 'Rural roads; no public transit. 10 miles from Machias.',
    broadband_availability: 'Very limited — satellite primary option.',
    water_access: 'Private wells; coastal saltwater access; freshwater ponds',
    working_waterfront: true,
    commercial_fishing_presence: true,
    aquaculture_presence: false,
    tourism_assets: [
      'Roque Bluffs State Park (sandy beach and freshwater pond)',
      'Schoppee Point',
      'Exceptional coastal scenery',
      'Birdwatching',
    ],
    natural_resources: ['Coastal shoreline', 'Roque Bluffs State Park', 'Freshwater ponds', 'Saltwater coves'],
    parks_and_recreation: ['Roque Bluffs State Park', 'Beach access', 'Kayaking'],
    local_institutions: ['Roque Bluffs Town Office'],
    school_system: 'Machias-area schools (AOS 96)',
    healthcare_access: 'Relies on Machias and Jonesport services',
    municipal_services: 'Minimal — volunteer fire; contracts most services',
    economic_development_opportunities: [
      'Ecotourism expansion',
      'Remote worker attraction',
      'Aquaculture potential',
      'Vacation rental market',
    ],
    community_assets: ['State Park', 'Coastal access', 'Low density rural environment', 'High scenic value'],
    community_challenges: [
      'Very small tax base',
      'Seasonal population fluctuation',
      'Limited year-round services',
      'Aging permanent population',
      'Broadband critical gap',
    ],
    planning_priorities: [
      'Broadband connectivity',
      'Seasonal to year-round conversion',
      'State Park partnership',
      'Municipal capacity',
    ],
    regional_connections: ['Machias', 'Jonesport'],
    profile_url: 'https://sunrisecounty.org/communities/roque-bluffs/',
    planning_map_url: null,
  },

  Jonesboro: {
    town_name: 'Jonesboro',
    county: 'Washington County',
    population: 587,
    median_age: 48.5,
    households: 280,
    median_household_income: 39200,
    labor_force: 265,
    employment: 248,
    major_employers: ['Forestry and logging', 'Jonesboro school system', 'Agriculture'],
    industry_sectors: ['Forestry', 'Agriculture', 'Construction', 'Government'],
    education_levels: {
      high_school_or_higher: '85%',
      bachelors_or_higher: '14%',
    },
    housing_units: 380,
    housing_occupancy: '73.7%',
    median_home_value: 108000,
    transportation_access: 'US Route 1 frontage. Rural network.',
    broadband_availability: 'Limited DSL along Route 1; no fiber.',
    water_access: 'Private wells; Chandler River frontage',
    working_waterfront: false,
    commercial_fishing_presence: false,
    aquaculture_presence: false,
    tourism_assets: ['Rural setting', 'River access', 'Proximity to Jonesport/Beals'],
    natural_resources: ['Chandler River', 'Forest land', 'Agricultural fields'],
    parks_and_recreation: ['River fishing', 'Hunting access'],
    local_institutions: ['Jonesboro Town Office', 'Local churches'],
    school_system: 'AOS 96 region',
    healthcare_access: 'Relies on Machias or Jonesport',
    municipal_services: 'Basic — road maintenance, volunteer fire',
    economic_development_opportunities: [
      'Forest products',
      'Agricultural land use',
      'Rural broadband',
      'Route 1 commercial development',
    ],
    community_assets: ['Route 1 location', 'Forest resources', 'Low land costs'],
    community_challenges: ['Small tax base', 'Limited services', 'Aging population', 'Workforce gaps'],
    planning_priorities: ['Broadband', 'Economic base', 'Infrastructure upkeep'],
    regional_connections: ['Jonesport', 'Machias', 'Whitneyville'],
    profile_url: 'https://sunrisecounty.org/communities/jonesboro/',
    planning_map_url: null,
  },

  Jonesport: {
    town_name: 'Jonesport',
    county: 'Washington County',
    population: 1357,
    median_age: 46.2,
    households: 633,
    median_household_income: 36800,
    labor_force: 610,
    employment: 555,
    major_employers: [
      'Commercial fishing fleet',
      'Jonesport-Beals High School',
      'Marine trades and boat building',
      'Lobster dealers and processors',
      'Town of Jonesport',
    ],
    industry_sectors: ['Commercial Fishing', 'Marine Trades', 'Education', 'Government', 'Tourism'],
    education_levels: {
      high_school_or_higher: '84%',
      bachelors_or_higher: '15%',
    },
    housing_units: 788,
    housing_occupancy: '80.3%',
    median_home_value: 112000,
    transportation_access: 'ME Route 187; bridge connection to Beals Island. Isolated peninsular geography.',
    broadband_availability: 'Partial — fiber through ConnectMaine initiative; coverage gaps.',
    water_access: 'Moosabec Reach; extensive harbor and working waterfront',
    working_waterfront: true,
    commercial_fishing_presence: true,
    aquaculture_presence: true,
    tourism_assets: [
      'Moosabec Reach scenic views',
      'Lobster boat building heritage',
      'Sawyer Memorial Bridge',
      'Coastal access',
      'Wild Maine lobster experience',
    ],
    natural_resources: ['Moosabec Reach', 'Coastal habitat', 'Island geography', 'Fishery resources'],
    parks_and_recreation: ['Coastal access points', 'Harbor walk', 'Fishing'],
    local_institutions: [
      'Jonesport-Beals High School',
      'Sawyer Memorial Library',
      'Jonesport Marina',
      'Fishermen\'s co-op infrastructure',
    ],
    school_system: 'Jonesport-Beals High School (regional); Elementary in town',
    healthcare_access: 'Jonesport Health Center (primary care); Emergency via Machias (40 mi)',
    municipal_services: 'Police, fire, EMS, public works, harbor master',
    economic_development_opportunities: [
      'Marine economy expansion',
      'Aquaculture permitting and infrastructure',
      'Working waterfront preservation and investment',
      'Tourism and heritage economy',
      'Boat building revival',
      'Broadband for remote workers',
    ],
    community_assets: [
      'Active commercial fishing fleet',
      'Strong maritime identity',
      'Working waterfront infrastructure',
      'Regional school',
      'High social cohesion',
    ],
    community_challenges: [
      'Economic concentration in lobster fishery',
      'Climate and ocean change risk',
      'Youth outmigration',
      'Limited land for development',
      'Peninsular isolation',
      'Healthcare access distance',
    ],
    planning_priorities: [
      'Waterfront access preservation',
      'Marine economy diversification',
      'Housing stock improvement',
      'Healthcare access',
      'Broadband connectivity',
    ],
    regional_connections: ['Beals', 'Jonesboro', 'Machias', 'Roque Bluffs'],
    profile_url: 'https://sunrisecounty.org/communities/jonesport/',
    planning_map_url: 'https://scec.maps.arcgis.com/apps/mapviewer/index.html?webmap=e09b62bf070240da8025292c8914536a',
  },

  Beals: {
    town_name: 'Beals',
    county: 'Washington County',
    population: 485,
    median_age: 47.8,
    households: 226,
    median_household_income: 34200,
    labor_force: 220,
    employment: 200,
    major_employers: ['Commercial lobster fishing', 'Beals Island boat builders', 'Lobster dealers'],
    industry_sectors: ['Commercial Fishing', 'Boat Building', 'Marine Trades'],
    education_levels: {
      high_school_or_higher: '82%',
      bachelors_or_higher: '11%',
    },
    housing_units: 310,
    housing_occupancy: '72.9%',
    median_home_value: 98500,
    transportation_access: 'Bridge to Jonesport (ME-187). Island community.',
    broadband_availability: 'Very limited.',
    water_access: 'Island; Moosabec Reach; extensive coastal access',
    working_waterfront: true,
    commercial_fishing_presence: true,
    aquaculture_presence: true,
    tourism_assets: ['Beals Island boat building heritage', 'Waterfront access', 'Island character'],
    natural_resources: ['Coastal island habitat', 'Fishery access', 'Scenic waters'],
    parks_and_recreation: ['Coastal access', 'Fishing and boating'],
    local_institutions: ['Beals Town Office', 'Local churches'],
    school_system: 'Jonesport-Beals (shared regional school)',
    healthcare_access: 'Relies on Jonesport Health Center and Machias hospital',
    municipal_services: 'Minimal — volunteer fire, basic road maintenance',
    economic_development_opportunities: [
      'Traditional boat building revival',
      'Aquaculture expansion',
      'Heritage tourism',
      'Cooperative fishing infrastructure',
    ],
    community_assets: ['Boat building tradition', 'Island cohesion', 'Working waterfront', 'Fishing heritage'],
    community_challenges: [
      'Very small tax base',
      'Island infrastructure costs',
      'Youth outmigration',
      'Climate/sea level vulnerability',
      'Economic concentration',
    ],
    planning_priorities: ['Infrastructure resilience', 'Waterfront preservation', 'Economic diversification', 'Broadband'],
    regional_connections: ['Jonesport', 'Jonesboro'],
    profile_url: 'https://sunrisecounty.org/communities/beals/',
    planning_map_url: null,
  },

  Cutler: {
    town_name: 'Cutler',
    county: 'Washington County',
    population: 481,
    median_age: 51.2,
    households: 235,
    median_household_income: 35600,
    labor_force: 200,
    employment: 185,
    major_employers: ['Commercial fishing', 'US Navy (former Cutler Naval Station — now NSA Cutler)', 'Tourism seasonal'],
    industry_sectors: ['Commercial Fishing', 'Government/Defense', 'Tourism', 'Forestry'],
    education_levels: {
      high_school_or_higher: '83%',
      bachelors_or_higher: '13%',
    },
    housing_units: 348,
    housing_occupancy: '67.5%',
    median_home_value: 115000,
    transportation_access: 'Route 191 — "Bold Coast" scenic byway. Isolated.',
    broadband_availability: 'Very limited.',
    water_access: 'Direct coastal access; Little Machias Bay; working harbor',
    working_waterfront: true,
    commercial_fishing_presence: true,
    aquaculture_presence: false,
    tourism_assets: [
      'Bold Coast Scenic Byway',
      'Cutler Coast Public Reserved Land (12,000+ acres)',
      'Dramatic cliffs and headlands',
      'Puffin habitat proximity',
      'Dark sky area',
    ],
    natural_resources: ['Bold Coast headlands', 'Cutler Coast Reserve', 'Old-growth forest', 'Coastal fisheries'],
    parks_and_recreation: ['Cutler Coast Trail System', 'Bold Coast hiking', 'Sea kayaking'],
    local_institutions: ['Cutler Town Office', 'NSA Cutler (Navy)', 'Bold Coast Association'],
    school_system: 'AOS 96 — small local school',
    healthcare_access: 'Relies on Machias (approx. 25 miles)',
    municipal_services: 'Minimal — volunteer fire; limited services',
    economic_development_opportunities: [
      'Ecotourism and adventure tourism (Bold Coast)',
      'Dark sky tourism',
      'Aquaculture potential',
      'Remote worker attraction',
      'NSA Cutler workforce',
    ],
    community_assets: ['World-class coastal scenery', 'Cutler Coast Reserve', 'Working harbor', 'Low density'],
    community_challenges: ['Very small tax base', 'Distance from services', 'Aging population', 'Broadband gap', 'Seasonal economy'],
    planning_priorities: ['Bold Coast protection and promotion', 'Broadband', 'Year-round economy', 'Infrastructure'],
    regional_connections: ['Whiting', 'Machias', 'Lubec'],
    profile_url: 'https://sunrisecounty.org/communities/cutler/',
    planning_map_url: null,
  },

  Whiting: {
    town_name: 'Whiting',
    county: 'Washington County',
    population: 421,
    median_age: 49.3,
    households: 203,
    median_household_income: 38100,
    labor_force: 190,
    employment: 175,
    major_employers: ['Forestry/logging', 'Agriculture', 'Small businesses'],
    industry_sectors: ['Forestry', 'Agriculture', 'Construction', 'Retail'],
    education_levels: {
      high_school_or_higher: '85%',
      bachelors_or_higher: '14%',
    },
    housing_units: 318,
    housing_occupancy: '63.8%',
    median_home_value: 104000,
    transportation_access: 'US Route 1; rural network.',
    broadband_availability: 'Limited.',
    water_access: 'Private wells; Cobscook Bay watershed',
    working_waterfront: false,
    commercial_fishing_presence: false,
    aquaculture_presence: false,
    tourism_assets: ['Rural scenery', 'Route 1 corridor', 'Proximity to Bold Coast and Cobscook Bay'],
    natural_resources: ['Forest land', 'Agricultural fields', 'Coastal watershed'],
    parks_and_recreation: ['Hunting', 'Fishing', 'Rural recreation'],
    local_institutions: ['Whiting Town Office'],
    school_system: 'AOS 96 area',
    healthcare_access: 'Relies on Machias or Lubec',
    municipal_services: 'Basic — road maintenance, volunteer fire',
    economic_development_opportunities: ['Forest products', 'Agricultural', 'Route 1 commercial', 'Broadband'],
    community_assets: ['Route 1 access', 'Forest and agricultural land', 'Low land costs'],
    community_challenges: ['Small tax base', 'Limited services', 'Population decline', 'Aging demographics'],
    planning_priorities: ['Broadband', 'Infrastructure', 'Economic base'],
    regional_connections: ['Cutler', 'Machias', 'Lubec'],
    profile_url: 'https://sunrisecounty.org/communities/whiting/',
    planning_map_url: null,
  },

  Whitneyville: {
    town_name: 'Whitneyville',
    county: 'Washington County',
    population: 401,
    median_age: 45.8,
    households: 192,
    median_household_income: 36500,
    labor_force: 185,
    employment: 170,
    major_employers: ['Whitneyville Wood Products', 'Agriculture', 'Machias-area employers'],
    industry_sectors: ['Forest Products', 'Agriculture', 'Manufacturing', 'Government'],
    education_levels: {
      high_school_or_higher: '84%',
      bachelors_or_higher: '12%',
    },
    housing_units: 246,
    housing_occupancy: '78.0%',
    median_home_value: 98000,
    transportation_access: 'Route 192; close proximity to Machias.',
    broadband_availability: 'Limited.',
    water_access: 'Private wells; Machias River watershed',
    working_waterfront: false,
    commercial_fishing_presence: false,
    aquaculture_presence: false,
    tourism_assets: ['Rural character', 'Forest access'],
    natural_resources: ['Forest land', 'Machias River watershed', 'Agricultural land'],
    parks_and_recreation: ['Hunting', 'Fishing', 'Forest recreation'],
    local_institutions: ['Whitneyville Town Office', 'Local churches'],
    school_system: 'Machias area — AOS 96 (SAD 37)',
    healthcare_access: 'Close to Machias — Down East Community Hospital',
    municipal_services: 'Basic — road maintenance, volunteer fire/EMS shared with Machias',
    economic_development_opportunities: [
      'Forest products manufacturing',
      'Proximity to Machias services and employment',
      'Interlocal service agreements',
      'Broadband expansion',
    ],
    community_assets: ['Proximity to Machias', 'Forest industry', 'Low land costs', 'Quiet rural character'],
    community_challenges: ['Very small tax base', 'Limited municipal capacity', 'Aging demographics', 'Broadband'],
    planning_priorities: ['Regional service sharing with Machias', 'Broadband', 'Economic base', 'Infrastructure'],
    regional_connections: ['Machias', 'East Machias', 'Marshfield'],
    profile_url: 'https://sunrisecounty.org/communities/whitneyville/',
    planning_map_url: null,
    note: 'Active interlocal agreement candidate with Machias for municipal finance services.',
  },

  Marshfield: {
    town_name: 'Marshfield',
    county: 'Washington County',
    population: 447,
    median_age: 46.5,
    households: 213,
    median_household_income: 37800,
    labor_force: 200,
    employment: 185,
    major_employers: ['Forestry', 'Agriculture', 'Machias area employers', 'Small businesses'],
    industry_sectors: ['Forestry', 'Agriculture', 'Construction', 'Government'],
    education_levels: {
      high_school_or_higher: '83%',
      bachelors_or_higher: '11%',
    },
    housing_units: 290,
    housing_occupancy: '73.4%',
    median_home_value: 96000,
    transportation_access: 'Route 192; rural roads. Close to Machias.',
    broadband_availability: 'Very limited.',
    water_access: 'Private wells; Machias River tributary',
    working_waterfront: false,
    commercial_fishing_presence: false,
    aquaculture_presence: false,
    tourism_assets: ['Rural scenery', 'Forest access'],
    natural_resources: ['Forest land', 'Agricultural land', 'River tributary access'],
    parks_and_recreation: ['Hunting', 'Fishing', 'Rural trails'],
    local_institutions: ['Marshfield Town Office'],
    school_system: 'Machias area schools (AOS 96)',
    healthcare_access: 'Relies on Machias — Down East Community Hospital',
    municipal_services: 'Minimal — road maintenance, volunteer fire',
    economic_development_opportunities: ['Forest products', 'Agricultural expansion', 'Broadband', 'Proximity to Machias'],
    community_assets: ['Rural land availability', 'Proximity to Machias', 'Forest resources'],
    community_challenges: ['Very small tax base', 'Limited municipal capacity', 'Population decline', 'Broadband gap'],
    planning_priorities: ['Regional service sharing', 'Broadband', 'Infrastructure maintenance'],
    regional_connections: ['Machias', 'East Machias', 'Whitneyville'],
    profile_url: 'https://sunrisecounty.org/communities/marshfield/',
    planning_map_url: null,
    note: 'Regional service agreement candidate with Machias for municipal finance services.',
  },

  Wesley: {
    town_name: 'Wesley',
    county: 'Washington County',
    population: 186,
    median_age: 52.1,
    households: 93,
    median_household_income: 39500,
    labor_force: 80,
    employment: 75,
    major_employers: ['Forestry and logging', 'Recreational camps', 'Remote work'],
    industry_sectors: ['Forestry', 'Recreation', 'Agriculture'],
    education_levels: {
      high_school_or_higher: '86%',
      bachelors_or_higher: '16%',
    },
    housing_units: 178,
    housing_occupancy: '52.2%',
    median_home_value: 102000,
    transportation_access: 'Route 9 ("Airline Highway"); rural isolation.',
    broadband_availability: 'Very limited — satellite primary.',
    water_access: 'Private wells; Machias River headwaters region; lakes and ponds',
    working_waterfront: false,
    commercial_fishing_presence: false,
    aquaculture_presence: false,
    tourism_assets: ['Wilderness camping', 'Hunting and fishing', 'Route 9 corridor', 'Lake access'],
    natural_resources: ['Extensive forest land', 'Lakes and ponds', 'Wildlife habitat', 'Headwater streams'],
    parks_and_recreation: ['Hunting', 'Fishing', 'Snowmobile and ATV trails', 'Wilderness camping'],
    local_institutions: ['Wesley Town Office (part-time)'],
    school_system: 'AOS 96 region; limited local enrollment',
    healthcare_access: 'Relies on Machias (35+ miles)',
    municipal_services: 'Minimal — road maintenance only; volunteer emergency services',
    economic_development_opportunities: ['Recreational/outdoor economy', 'Remote worker attraction', 'Forest products', 'Broadband'],
    community_assets: ['Extensive natural resources', 'Low cost of living', 'Wilderness character', 'Route 9 access'],
    community_challenges: ['Very small population and tax base', 'Extreme service distance', 'Broadband absence', 'Aging demographics'],
    planning_priorities: ['Broadband', 'Emergency services access', 'Forest management'],
    regional_connections: ['Machias', 'Beddington', 'Clifton'],
    profile_url: 'https://sunrisecounty.org/communities/wesley/',
    planning_map_url: null,
  },

  Northfield: {
    town_name: 'Northfield',
    county: 'Washington County',
    population: 188,
    median_age: 50.3,
    households: 91,
    median_household_income: 36200,
    labor_force: 82,
    employment: 76,
    major_employers: ['Forestry and logging', 'Agriculture', 'Machias area employers'],
    industry_sectors: ['Forestry', 'Agriculture', 'Construction'],
    education_levels: {
      high_school_or_higher: '82%',
      bachelors_or_higher: '10%',
    },
    housing_units: 142,
    housing_occupancy: '64.1%',
    median_home_value: 89000,
    transportation_access: 'Route 9; rural roads. Isolated.',
    broadband_availability: 'Very limited.',
    water_access: 'Private wells; forest watershed access',
    working_waterfront: false,
    commercial_fishing_presence: false,
    aquaculture_presence: false,
    tourism_assets: ['Rural character', 'Hunting and fishing'],
    natural_resources: ['Forest land', 'Agricultural land', 'Watershed access'],
    parks_and_recreation: ['Hunting', 'Fishing', 'Snowmobile trails'],
    local_institutions: ['Northfield Town Office (part-time)'],
    school_system: 'AOS 96 region',
    healthcare_access: 'Relies on Machias',
    municipal_services: 'Minimal — road maintenance; volunteer fire',
    economic_development_opportunities: ['Forest products', 'Agricultural expansion', 'Broadband', 'Interlocal agreements'],
    community_assets: ['Forest resources', 'Low land costs', 'Rural character'],
    community_challenges: ['Very small tax base', 'Minimal municipal capacity', 'Population decline', 'Aging demographics', 'Broadband absence'],
    planning_priorities: ['Regional service sharing', 'Broadband', 'Infrastructure'],
    regional_connections: ['Machias', 'Wesley', 'Beddington'],
    profile_url: 'https://sunrisecounty.org/communities/northfield/',
    planning_map_url: null,
    note: 'Regional service agreement candidate with Machias for municipal finance services.',
  },
};

// Color scheme for map polygons
export const TOWN_FILL_COLORS = {
  Machias: '#1a6b5c',
  'East Machias': '#2a7a4a',
  'Roque Bluffs': '#2a5c7a',
  Jonesboro: '#5c3d8a',
  Jonesport: '#8a4020',
  Beals: '#8B2020',
  Cutler: '#3a5c3a',
  Whiting: '#7a5c1a',
  Whitneyville: '#1a3a5c',
  Marshfield: '#6b3a5c',
  Wesley: '#4a6b4a',
  Northfield: '#2a4c6b',
};

export const REGION_TOWNS = [
  'Machias', 'East Machias', 'Roque Bluffs', 'Jonesboro', 'Jonesport',
  'Beals', 'Cutler', 'Whiting', 'Whitneyville', 'Marshfield', 'Wesley', 'Northfield',
];

export const ARCGIS_URL =
  `https://services1.arcgis.com/RbMX0mRVOFNTdLzd/arcgis/rest/services/Maine_Town_and_Townships_Boundary_Polygons_Dissolved/FeatureServer/0/query?` +
  `where=TOWN%20IN%20('Machias','East%20Machias','Roque%20Bluffs','Jonesboro','Jonesport','Beals','Cutler','Whiting','Whitneyville','Marshfield','Wesley','Northfield')` +
  `&outFields=TOWN&outSR=4326&f=geojson`;